services:
  okbkm:
    image: okbkm
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080;https://+:8081"
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=okbkmDB;Username=postgres;Password=admin;
      KAFKA__BOOTSTRAP__SERVERS: kafka1:9092  # Kafka bağlantısı
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - my-network

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: okbkmDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - okbkm_pgdata_volume:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  okbkm_pgdata_volume:
    external: true

networks:
  my-network:
    external: true