services:
  okbkm:
    image: okbkm
    build:
      context: .
      dockerfile: OKbkm/Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080;https://+:8081"
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=okbkmDB;Username=postgres;Password=admin;
    ports:
      - "8080:8080"
      - "8081:8081"

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: okbkmDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - okbkm_pgdata_volume:/var/lib/postgresql/data

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: "kraft-cluster-1"
    volumes:
      - ./data/kafka1:/tmp/kraft-combined-logs

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka2
    ports:
      - "9094:9092"
    environment:
      KAFKA_KRAFT_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9092,CONTROLLER://kafka2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: "kraft-cluster-1"
    volumes:
      - ./data/kafka2:/tmp/kraft-combined-logs

  kafka3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka3
    ports:
      - "9096:9092"
    environment:
      KAFKA_KRAFT_BROKER_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9092,CONTROLLER://kafka3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: "kraft-cluster-1"
    volumes:
      - ./data/kafka3:/tmp/kraft-combined-logs

  kafka-init:
    restart: on-failure
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    entrypoint: ["/bin/sh", "-c"]
    command:
      kafka-topics --bootstrap-server kafka1:9092 \
        --create --if-not-exists --topic deposit --replication-factor 3 --partitions 1 &&
      kafka-topics --bootstrap-server kafka1:9092 \
        --create --if-not-exists --topic withdraw --replication-factor 3 --partitions 1 &&
      kafka-topics --bootstrap-server kafka1:9092 \
        --create --if-not-exists --topic transfer --replication-factor 3 --partitions 1

  akhq:
    image: tchiotludo/akhq:0.24.0
    container_name: akhq
    ports:
      - "8085:8080"  # 8085 dış erişim için
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          server:
            servlet:
              context-path: /
          connections:
            kraft-cluster:
              properties:
                bootstrap.servers: kafka1:9092,kafka2:9094,kafka3:9096

volumes:
  okbkm_pgdata_volume:
    external: true
